export const NOTIF_ACTIVITY_LOGIN = "LOGIN";
export const NOTIF_ACTIVITY_ZOOM_RECORDING_WEBHOOK = "ZOOM_RECORDING_WEBHOOK";
export const NOTIF_ACTIVITY_ZOOM_MONITORING_REQUIRED = "ZOOM_MONITORING_REQUIRED";
export const NOTIF_ACTIVITY_ZOOM_ASSISTANT_ASSIGNED = "ZOOM_ASSISTANT_ASSIGNED";
export const NOTIF_ACTIVITY_ZOOM_ASSISTANT_UNASSIGNED = "ZOOM_ASSISTANT_UNASSIGNED";
export const NOTIF_ACTIVITY_ZOOM_ASSISTANT_MEETING_UPDATED = "ZOOM_ASSISTANT_MEETING_UPDATED";
